import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Tapvey",
  description: "Terms governing use of the Tapvey website and services.",
};

export default function TermsOfService() {
  const S = {
    page: { fontFamily: "'DM Sans',sans-serif", background: "#F5E8CC", minHeight: "100vh", padding: "80px 5% 60px", color: "#1A1008" },
    container: { maxWidth: 720, margin: "0 auto" },
    h1: { fontFamily: "'Libre Baskerville',Georgia,serif", fontSize: 36, fontWeight: 700, marginBottom: 8 },
    updated: { fontSize: 14, color: "#6B503A", marginBottom: 40 },
    h2: { fontFamily: "'Libre Baskerville',Georgia,serif", fontSize: 22, fontWeight: 700, margin: "36px 0 12px" },
    p: { fontSize: 15, lineHeight: 1.75, color: "#1A1008", margin: "0 0 16px" },
    back: { display: "inline-block", marginTop: 32, fontSize: 14, color: "#B07820", textDecoration: "none" },
  };

  return (
    <div style={S.page}>
      <div style={S.container}>
        <Link href="/" style={S.back}>&larr; Back to Tapvey</Link>
        <h1 style={{ ...S.h1, marginTop: 24 }}>Terms of Service</h1>
        <p style={S.updated}>Last updated: 23 May 2026</p>

        <h2 style={S.h2}>Overview</h2>
        <p style={S.p}>These terms govern your use of tapvey.com and the Tapvey service operated by Tapvey Technologies Pvt Ltd. By using the site, you agree to these terms.</p>

        <h2 style={S.h2}>The service</h2>
        <p style={S.p}>Tapvey helps restaurant customers write and share reviews. We use AI (Google Gemini) to generate review text based on tags and ratings selected by the customer. The customer always has the opportunity to edit the generated text before sharing.</p>

        <h2 style={S.h2}>User responsibilities</h2>
        <p style={S.p}>You agree to provide accurate information when signing up for the waitlist. You agree not to use the service for any unlawful purpose, to generate fake or misleading reviews, or to abuse the AI generation feature.</p>

        <h2 style={S.h2}>AI-generated content</h2>
        <p style={S.p}>Reviews are generated by AI based on your inputs. You are responsible for reviewing and editing the generated text before posting it on any platform. Tapvey does not guarantee the accuracy or suitability of AI-generated content.</p>

        <h2 style={S.h2}>Intellectual property</h2>
        <p style={S.p}>The Tapvey name, logo, and website content are owned by Tapvey Technologies Pvt Ltd. Reviews you generate and post are your own.</p>

        <h2 style={S.h2}>Limitation of liability</h2>
        <p style={S.p}>Tapvey is provided &quot;as is&quot;. We are not liable for any damages arising from your use of the service, including any consequences of posting AI-generated reviews on third-party platforms.</p>

        <h2 style={S.h2}>Changes</h2>
        <p style={S.p}>We may update these terms at any time. Continued use of the site constitutes acceptance of the updated terms.</p>

        <h2 style={S.h2}>Contact</h2>
        <p style={S.p}>Questions? Email <a href="mailto:hello@tapvey.com" style={{ color: "#B07820" }}>hello@tapvey.com</a>.</p>

        <Link href="/" style={S.back}>&larr; Back to Tapvey</Link>
      </div>
    </div>
  );
}
